apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-llm-langchain
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/premrasapalli/rag-llm-langchain-deploy.git
    targetRevision: main
    path: k8s/overlays/gke
  destination:
    server: https://kubernetes.default.svc
    namespace: rag-llm-langchain
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true