apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embed-store
  namespace: rag-llm-langchain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: premium-rwo