apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embed-store
  namespace: genai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: premium-rwo