apiVersion: v1
kind: Service
metadata:
  name: serving-llm
  namespace: genai
  labels:
    app: serving-llm
spec:
  selector:
    app: serving-llm
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  type: ClusterIP
