apiVersion: v1
kind: Service
metadata:
  name: serving-embedding
  namespace: genai
  labels:
    app: serving-embedding
spec:
  selector:
    app: serving-embedding
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
  type: ClusterIP
